import pyautogui


pyautogui.hotkey("win", "r")
pyautogui.write("cmd")
pyautogui.press("enter")
while 0>1:
    pyautogui.write("color 12")
    pyautogui.press("enter")
    pyautogui.write("color 13")
    pyautogui.press("enter")
    pyautogui.write("color 14")
    pyautogui.press("enter")
    pyautogui.write("color 15")
    pyautogui.press("enter")
    pyautogui.write("color 16")
    pyautogui.press("enter")
    pyautogui.write("color 17")
    pyautogui.press("enter")
    pyautogui.write("color 18")
    pyautogui.press("enter")
    pyautogui.write("color 19")
    pyautogui.press("enter")
    pyautogui.write("color 1A")
    pyautogui.press("enter")
    pyautogui.write("color 1B")
    pyautogui.press("enter")
    pyautogui.write("color 1C")
    pyautogui.press("enter")
    pyautogui.write("color 1D")
    pyautogui.press("enter")
    pyautogui.write("color 1E")
    pyautogui.press("enter")
